### PR TITLE
Escape HTML code properly

### PR DESCRIPTION
**Pull request by sskras**
Also fix the `<sub>` tag.

### CODE REVIEW

**Comment by s-leroux** [comment]
Thanks, Saulius. Good catch!

I should have used the proper Asciidoctor syntax for superscript:
https://docs.asciidoctor.org/asciidoc/latest/text/subscript-and-superscript/

Could you update your PR to replace `<sup>2</sup>` by `^2^` ?

**Comment by sskras** [comment]
Thanks for reminding me about this Asciidoc ability, I used your tip.

I did a forced push onto the same branch. Not sure about where the final commit message would come from.

**Comment by s-leroux** [comment]
Thanks. I will merge that this weekend

I will also add a 'contributors' or alike new header at the top of the document

**Comment by s-leroux** [comment]
@sskras: I merged the PR and then added your name as a contributor in the article header.

**Comment by sskras** [comment]
Oh, thanks!

**Pull request merged**
